---
# tasks file for package-security
- name: Install unattended upgrades package.
  apt: name=unattended-upgrades state=present
  when: ansible_os_family == 'Debian'

- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "../templates/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
  when: ansible_os_family == 'Debian'

- name: Install yum-cron.
  yum: name=yum-cron state=present
  when: ansible_os_family == 'RedHat'

- name: Ensure yum-cron is running and enabled on boot.
  service: name=yum-cron state=started enabled=yes
  when: ansible_os_family == 'RedHat'