---
# tasks file for package-security
- name: Install unattended upgrades package.
  apt: name=unattended-upgrades state=present
  when: ansible_os_family == 'Debian'

- name: Install yum-cron.
  yum: name=yum-cron state=present
  when: ansible_os_family == 'RedHat'

- name: Ensure yum-cron is running and enabled on boot.
  service: name=yum-cron state=started enabled=yes
  when: ansible_os_family == 'RedHat'