---
# tasks file for docker
- name: Download docker installer
  get_url:
    url: https://get.docker.com
    dest: /root/get-docker.sh

- name: Install docker
  shell: >
    sh /root/get-docker.sh
    creates=/usr/bin/docker

- name: Add {{ ssh_user }} to the docker group
  user:
    name: "{{ ssh_user }}"
    groups: docker
    append: yes

- name: Ensure docker is running and enabled on boot.
  service: name=docker state=started enabled=yes

# @see https://www.techrepublic.com/article/how-to-fix-the-docker-and-ufw-security-flaw/
# @see https://blog.viktorpetersson.com/2014/11/03/the-dangers-of-ufw-docker.html
- name: Fix docker's iptables bug by disabling iptables in docker daemon
  lineinfile:
    dest: /etc/default/docker
    regexp: "DOCKER_OPTS="
    line: 'DOCKER_OPTS="--iptables=false"'
  when: ansible_os_family == 'Debian'
  notify: restart docker
